# Generated by Django 4.2.2 on 2023-07-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_remove_card_category_category_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori'),
        ),
    ]
