# Generated by Django 4.2.2 on 2023-07-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_remove_category_cards_card_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='cards',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.card', verbose_name='Kartlar'),
        ),
    ]
