# Generated by Django 4.2.2 on 2023-07-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_type_alter_card_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Types',
        ),
    ]
