# Generated by Django 4.2.2 on 2023-07-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0009_type_alter_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='like',
            field=models.BooleanField(null=True, verbose_name='Favori Mi?'),
        ),
    ]
